[package]
name = "horrid-vec"
version = "0.1.0"
authors = ["Hagsteel <me@hagsteel.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
criterion = "0.3.3"

[[bench]]
name = "bench"
harness = false
